In [8]:

7

matrix=[]
for k in range(4):
  r=[]
  for h in range(4):
    r.append(int(input()))
  matrix.append(r)
transpose=[]
for t in range(4):
  transpose.append([])
  for u in range(4):
   num=matrix[u][t]
   transpose[t].append(num)
print('Transpose matrix:')
for i in range(4):
  for j in range(4):
    print(transpose[i][j],end='')
  print()
import numpy as np
mat=np.transpose(matrix)
print(mat)
print(mat.reshape(2,8))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
[[ 1  5  9 13  2  6 10 14]
 [ 3  7 11 15  4  8 12 16]]
